// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v4.24.3
// source: proto/accrual_status_transition.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccrualStatusTransition struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status         string       `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NextStatus     string       `protobuf:"bytes,2,opt,name=next_status,json=nextStatus,proto3" json:"next_status,omitempty"`
	PaymentType    PaymentType  `protobuf:"varint,3,opt,name=payment_type,json=paymentType,proto3,enum=PaymentType" json:"payment_type,omitempty"`
	IsExternalFlow bool         `protobuf:"varint,4,opt,name=is_external_flow,json=isExternalFlow,proto3" json:"is_external_flow,omitempty"`
	SideDeal       SideDealType `protobuf:"varint,5,opt,name=side_deal,json=sideDeal,proto3,enum=SideDealType" json:"side_deal,omitempty"`
}

func (x *AccrualStatusTransition) Reset() {
	*x = AccrualStatusTransition{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_accrual_status_transition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccrualStatusTransition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccrualStatusTransition) ProtoMessage() {}

func (x *AccrualStatusTransition) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accrual_status_transition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccrualStatusTransition.ProtoReflect.Descriptor instead.
func (*AccrualStatusTransition) Descriptor() ([]byte, []int) {
	return file_proto_accrual_status_transition_proto_rawDescGZIP(), []int{0}
}

func (x *AccrualStatusTransition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *AccrualStatusTransition) GetNextStatus() string {
	if x != nil {
		return x.NextStatus
	}
	return ""
}

func (x *AccrualStatusTransition) GetPaymentType() PaymentType {
	if x != nil {
		return x.PaymentType
	}
	return PaymentType_PAYMENT_TYPE_UNKNOWN
}

func (x *AccrualStatusTransition) GetIsExternalFlow() bool {
	if x != nil {
		return x.IsExternalFlow
	}
	return false
}

func (x *AccrualStatusTransition) GetSideDeal() SideDealType {
	if x != nil {
		return x.SideDeal
	}
	return SideDealType_SIDE_DEAL_TYPE_UNKNOWN
}

var File_proto_accrual_status_transition_proto protoreflect.FileDescriptor

var file_proto_accrual_status_transition_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61, 0x63, 0x63, 0x72, 0x75, 0x61, 0x6c, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x18, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x69, 0x64, 0x65, 0x5f, 0x64, 0x65,
	0x61, 0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xd9, 0x01,
	0x0a, 0x17, 0x41, 0x63, 0x63, 0x72, 0x75, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x6e, 0x65, 0x78, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x65, 0x78, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x2f, 0x0a, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0c, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x69, 0x73, 0x5f, 0x65, 0x78, 0x74, 0x65, 0x72, 0x6e,
	0x61, 0x6c, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0e, 0x69,
	0x73, 0x45, 0x78, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x46, 0x6c, 0x6f, 0x77, 0x12, 0x2a, 0x0a,
	0x09, 0x73, 0x69, 0x64, 0x65, 0x5f, 0x64, 0x65, 0x61, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0d, 0x2e, 0x53, 0x69, 0x64, 0x65, 0x44, 0x65, 0x61, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x08, 0x73, 0x69, 0x64, 0x65, 0x44, 0x65, 0x61, 0x6c, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6c, 0x65, 0x78, 0x4b, 0x65, 0x6e, 0x62,
	0x6f, 0x2f, 0x64, 0x69, 0x63, 0x74, 0x75, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_accrual_status_transition_proto_rawDescOnce sync.Once
	file_proto_accrual_status_transition_proto_rawDescData = file_proto_accrual_status_transition_proto_rawDesc
)

func file_proto_accrual_status_transition_proto_rawDescGZIP() []byte {
	file_proto_accrual_status_transition_proto_rawDescOnce.Do(func() {
		file_proto_accrual_status_transition_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_accrual_status_transition_proto_rawDescData)
	})
	return file_proto_accrual_status_transition_proto_rawDescData
}

var file_proto_accrual_status_transition_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_accrual_status_transition_proto_goTypes = []any{
	(*AccrualStatusTransition)(nil), // 0: AccrualStatusTransition
	(PaymentType)(0),                // 1: PaymentType
	(SideDealType)(0),               // 2: SideDealType
}
var file_proto_accrual_status_transition_proto_depIdxs = []int32{
	1, // 0: AccrualStatusTransition.payment_type:type_name -> PaymentType
	2, // 1: AccrualStatusTransition.side_deal:type_name -> SideDealType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_accrual_status_transition_proto_init() }
func file_proto_accrual_status_transition_proto_init() {
	if File_proto_accrual_status_transition_proto != nil {
		return
	}
	file_proto_payment_type_proto_init()
	file_proto_side_deal_type_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_proto_accrual_status_transition_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AccrualStatusTransition); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_accrual_status_transition_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_accrual_status_transition_proto_goTypes,
		DependencyIndexes: file_proto_accrual_status_transition_proto_depIdxs,
		MessageInfos:      file_proto_accrual_status_transition_proto_msgTypes,
	}.Build()
	File_proto_accrual_status_transition_proto = out.File
	file_proto_accrual_status_transition_proto_rawDesc = nil
	file_proto_accrual_status_transition_proto_goTypes = nil
	file_proto_accrual_status_transition_proto_depIdxs = nil
}
