// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: proto/fin_event.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FinEventClient is the client API for FinEvent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FinEventClient interface {
	ListSignatures(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListSignaturesResponse, error)
	ListComments(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error)
	CreateComment(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*Comment, error)
	UpdateComment(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*Comment, error)
	DeleteComment(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	CreatePermission(ctx context.Context, in *Permission, opts ...grpc.CallOption) (*Permission, error)
	ListPermissions(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error)
	DeletePermission(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ListActions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListActionsResponse, error)
	ListTransfers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListTransfersResponse, error)
	GetTransfer(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Transfer, error)
	CreateTransfer(ctx context.Context, in *Transfer, opts ...grpc.CallOption) (*Transfer, error)
	AllocateTransfer(ctx context.Context, in *AllocateTransferRequest, opts ...grpc.CallOption) (*Allocation, error)
	BatchInsertTransfers(ctx context.Context, in *BatchInsertTransfersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateTransfer(ctx context.Context, in *Transfer, opts ...grpc.CallOption) (*Transfer, error)
	AggregateTransfers(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*EventAggregate, error)
	// --
	ListAccruals(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListAccrualsResponse, error)
	GetAccrual(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Accrual, error)
	CreateAccrual(ctx context.Context, in *Accrual, opts ...grpc.CallOption) (*Accrual, error)
	UpdateAccrual(ctx context.Context, in *Accrual, opts ...grpc.CallOption) (*Accrual, error)
	AggregateAccruals(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*AccrualsAggregate, error)
	BatchInsertAccruals(ctx context.Context, in *BatchInsertAccrualsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GenerateAccrualPDF(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*FileResponse, error)
	// --
	ListProducts(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListProductsResponse, error)
	ListPositions(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListPositionsResponse, error)
	UpdatePosition(ctx context.Context, in *Position, opts ...grpc.CallOption) (*Position, error)
	BatchInsertPositions(ctx context.Context, in *BatchInsertPositionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// --
	ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error)
	GetArticle(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Article, error)
	CreateArticle(ctx context.Context, in *Article, opts ...grpc.CallOption) (*Article, error)
	UpdateArticle(ctx context.Context, in *Article, opts ...grpc.CallOption) (*Article, error)
	DeleteArticle(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// --
	ListAllocations(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListAllocationsResponse, error)
	CreateAllocation(ctx context.Context, in *Allocation, opts ...grpc.CallOption) (*Allocation, error)
}

type finEventClient struct {
	cc grpc.ClientConnInterface
}

func NewFinEventClient(cc grpc.ClientConnInterface) FinEventClient {
	return &finEventClient{cc}
}

func (c *finEventClient) ListSignatures(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListSignaturesResponse, error) {
	out := new(ListSignaturesResponse)
	err := c.cc.Invoke(ctx, "/FinEvent/ListSignatures", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) ListComments(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListCommentsResponse, error) {
	out := new(ListCommentsResponse)
	err := c.cc.Invoke(ctx, "/FinEvent/ListComments", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) CreateComment(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := c.cc.Invoke(ctx, "/FinEvent/CreateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) UpdateComment(ctx context.Context, in *Comment, opts ...grpc.CallOption) (*Comment, error) {
	out := new(Comment)
	err := c.cc.Invoke(ctx, "/FinEvent/UpdateComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) DeleteComment(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/FinEvent/DeleteComment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) CreatePermission(ctx context.Context, in *Permission, opts ...grpc.CallOption) (*Permission, error) {
	out := new(Permission)
	err := c.cc.Invoke(ctx, "/FinEvent/CreatePermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) ListPermissions(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListPermissionsResponse, error) {
	out := new(ListPermissionsResponse)
	err := c.cc.Invoke(ctx, "/FinEvent/ListPermissions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) DeletePermission(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/FinEvent/DeletePermission", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) ListActions(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*ListActionsResponse, error) {
	out := new(ListActionsResponse)
	err := c.cc.Invoke(ctx, "/FinEvent/ListActions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) ListTransfers(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListTransfersResponse, error) {
	out := new(ListTransfersResponse)
	err := c.cc.Invoke(ctx, "/FinEvent/ListTransfers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) GetTransfer(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Transfer, error) {
	out := new(Transfer)
	err := c.cc.Invoke(ctx, "/FinEvent/GetTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) CreateTransfer(ctx context.Context, in *Transfer, opts ...grpc.CallOption) (*Transfer, error) {
	out := new(Transfer)
	err := c.cc.Invoke(ctx, "/FinEvent/CreateTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) AllocateTransfer(ctx context.Context, in *AllocateTransferRequest, opts ...grpc.CallOption) (*Allocation, error) {
	out := new(Allocation)
	err := c.cc.Invoke(ctx, "/FinEvent/AllocateTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) BatchInsertTransfers(ctx context.Context, in *BatchInsertTransfersRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/FinEvent/BatchInsertTransfers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) UpdateTransfer(ctx context.Context, in *Transfer, opts ...grpc.CallOption) (*Transfer, error) {
	out := new(Transfer)
	err := c.cc.Invoke(ctx, "/FinEvent/UpdateTransfer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) AggregateTransfers(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*EventAggregate, error) {
	out := new(EventAggregate)
	err := c.cc.Invoke(ctx, "/FinEvent/AggregateTransfers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) ListAccruals(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListAccrualsResponse, error) {
	out := new(ListAccrualsResponse)
	err := c.cc.Invoke(ctx, "/FinEvent/ListAccruals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) GetAccrual(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Accrual, error) {
	out := new(Accrual)
	err := c.cc.Invoke(ctx, "/FinEvent/GetAccrual", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) CreateAccrual(ctx context.Context, in *Accrual, opts ...grpc.CallOption) (*Accrual, error) {
	out := new(Accrual)
	err := c.cc.Invoke(ctx, "/FinEvent/CreateAccrual", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) UpdateAccrual(ctx context.Context, in *Accrual, opts ...grpc.CallOption) (*Accrual, error) {
	out := new(Accrual)
	err := c.cc.Invoke(ctx, "/FinEvent/UpdateAccrual", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) AggregateAccruals(ctx context.Context, in *AggregateRequest, opts ...grpc.CallOption) (*AccrualsAggregate, error) {
	out := new(AccrualsAggregate)
	err := c.cc.Invoke(ctx, "/FinEvent/AggregateAccruals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) BatchInsertAccruals(ctx context.Context, in *BatchInsertAccrualsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/FinEvent/BatchInsertAccruals", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) GenerateAccrualPDF(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*FileResponse, error) {
	out := new(FileResponse)
	err := c.cc.Invoke(ctx, "/FinEvent/GenerateAccrualPDF", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) ListProducts(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListProductsResponse, error) {
	out := new(ListProductsResponse)
	err := c.cc.Invoke(ctx, "/FinEvent/ListProducts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) ListPositions(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListPositionsResponse, error) {
	out := new(ListPositionsResponse)
	err := c.cc.Invoke(ctx, "/FinEvent/ListPositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) UpdatePosition(ctx context.Context, in *Position, opts ...grpc.CallOption) (*Position, error) {
	out := new(Position)
	err := c.cc.Invoke(ctx, "/FinEvent/UpdatePosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) BatchInsertPositions(ctx context.Context, in *BatchInsertPositionsRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/FinEvent/BatchInsertPositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) ListArticles(ctx context.Context, in *ListArticlesRequest, opts ...grpc.CallOption) (*ListArticlesResponse, error) {
	out := new(ListArticlesResponse)
	err := c.cc.Invoke(ctx, "/FinEvent/ListArticles", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) GetArticle(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*Article, error) {
	out := new(Article)
	err := c.cc.Invoke(ctx, "/FinEvent/GetArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) CreateArticle(ctx context.Context, in *Article, opts ...grpc.CallOption) (*Article, error) {
	out := new(Article)
	err := c.cc.Invoke(ctx, "/FinEvent/CreateArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) UpdateArticle(ctx context.Context, in *Article, opts ...grpc.CallOption) (*Article, error) {
	out := new(Article)
	err := c.cc.Invoke(ctx, "/FinEvent/UpdateArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) DeleteArticle(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/FinEvent/DeleteArticle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) ListAllocations(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListAllocationsResponse, error) {
	out := new(ListAllocationsResponse)
	err := c.cc.Invoke(ctx, "/FinEvent/ListAllocations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *finEventClient) CreateAllocation(ctx context.Context, in *Allocation, opts ...grpc.CallOption) (*Allocation, error) {
	out := new(Allocation)
	err := c.cc.Invoke(ctx, "/FinEvent/CreateAllocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FinEventServer is the server API for FinEvent service.
// All implementations must embed UnimplementedFinEventServer
// for forward compatibility
type FinEventServer interface {
	ListSignatures(context.Context, *ListRequest) (*ListSignaturesResponse, error)
	ListComments(context.Context, *ListRequest) (*ListCommentsResponse, error)
	CreateComment(context.Context, *Comment) (*Comment, error)
	UpdateComment(context.Context, *Comment) (*Comment, error)
	DeleteComment(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	CreatePermission(context.Context, *Permission) (*Permission, error)
	ListPermissions(context.Context, *ListRequest) (*ListPermissionsResponse, error)
	DeletePermission(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	ListActions(context.Context, *emptypb.Empty) (*ListActionsResponse, error)
	ListTransfers(context.Context, *ListRequest) (*ListTransfersResponse, error)
	GetTransfer(context.Context, *GetRequest) (*Transfer, error)
	CreateTransfer(context.Context, *Transfer) (*Transfer, error)
	AllocateTransfer(context.Context, *AllocateTransferRequest) (*Allocation, error)
	BatchInsertTransfers(context.Context, *BatchInsertTransfersRequest) (*emptypb.Empty, error)
	UpdateTransfer(context.Context, *Transfer) (*Transfer, error)
	AggregateTransfers(context.Context, *AggregateRequest) (*EventAggregate, error)
	// --
	ListAccruals(context.Context, *ListRequest) (*ListAccrualsResponse, error)
	GetAccrual(context.Context, *GetRequest) (*Accrual, error)
	CreateAccrual(context.Context, *Accrual) (*Accrual, error)
	UpdateAccrual(context.Context, *Accrual) (*Accrual, error)
	AggregateAccruals(context.Context, *AggregateRequest) (*AccrualsAggregate, error)
	BatchInsertAccruals(context.Context, *BatchInsertAccrualsRequest) (*emptypb.Empty, error)
	GenerateAccrualPDF(context.Context, *GetRequest) (*FileResponse, error)
	// --
	ListProducts(context.Context, *ListRequest) (*ListProductsResponse, error)
	ListPositions(context.Context, *ListRequest) (*ListPositionsResponse, error)
	UpdatePosition(context.Context, *Position) (*Position, error)
	BatchInsertPositions(context.Context, *BatchInsertPositionsRequest) (*emptypb.Empty, error)
	// --
	ListArticles(context.Context, *ListArticlesRequest) (*ListArticlesResponse, error)
	GetArticle(context.Context, *GetRequest) (*Article, error)
	CreateArticle(context.Context, *Article) (*Article, error)
	UpdateArticle(context.Context, *Article) (*Article, error)
	DeleteArticle(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	// --
	ListAllocations(context.Context, *ListRequest) (*ListAllocationsResponse, error)
	CreateAllocation(context.Context, *Allocation) (*Allocation, error)
	mustEmbedUnimplementedFinEventServer()
}

// UnimplementedFinEventServer must be embedded to have forward compatible implementations.
type UnimplementedFinEventServer struct {
}

func (UnimplementedFinEventServer) ListSignatures(context.Context, *ListRequest) (*ListSignaturesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSignatures not implemented")
}
func (UnimplementedFinEventServer) ListComments(context.Context, *ListRequest) (*ListCommentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListComments not implemented")
}
func (UnimplementedFinEventServer) CreateComment(context.Context, *Comment) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateComment not implemented")
}
func (UnimplementedFinEventServer) UpdateComment(context.Context, *Comment) (*Comment, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateComment not implemented")
}
func (UnimplementedFinEventServer) DeleteComment(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteComment not implemented")
}
func (UnimplementedFinEventServer) CreatePermission(context.Context, *Permission) (*Permission, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePermission not implemented")
}
func (UnimplementedFinEventServer) ListPermissions(context.Context, *ListRequest) (*ListPermissionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPermissions not implemented")
}
func (UnimplementedFinEventServer) DeletePermission(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePermission not implemented")
}
func (UnimplementedFinEventServer) ListActions(context.Context, *emptypb.Empty) (*ListActionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListActions not implemented")
}
func (UnimplementedFinEventServer) ListTransfers(context.Context, *ListRequest) (*ListTransfersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransfers not implemented")
}
func (UnimplementedFinEventServer) GetTransfer(context.Context, *GetRequest) (*Transfer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTransfer not implemented")
}
func (UnimplementedFinEventServer) CreateTransfer(context.Context, *Transfer) (*Transfer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTransfer not implemented")
}
func (UnimplementedFinEventServer) AllocateTransfer(context.Context, *AllocateTransferRequest) (*Allocation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AllocateTransfer not implemented")
}
func (UnimplementedFinEventServer) BatchInsertTransfers(context.Context, *BatchInsertTransfersRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchInsertTransfers not implemented")
}
func (UnimplementedFinEventServer) UpdateTransfer(context.Context, *Transfer) (*Transfer, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTransfer not implemented")
}
func (UnimplementedFinEventServer) AggregateTransfers(context.Context, *AggregateRequest) (*EventAggregate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregateTransfers not implemented")
}
func (UnimplementedFinEventServer) ListAccruals(context.Context, *ListRequest) (*ListAccrualsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccruals not implemented")
}
func (UnimplementedFinEventServer) GetAccrual(context.Context, *GetRequest) (*Accrual, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccrual not implemented")
}
func (UnimplementedFinEventServer) CreateAccrual(context.Context, *Accrual) (*Accrual, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccrual not implemented")
}
func (UnimplementedFinEventServer) UpdateAccrual(context.Context, *Accrual) (*Accrual, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccrual not implemented")
}
func (UnimplementedFinEventServer) AggregateAccruals(context.Context, *AggregateRequest) (*AccrualsAggregate, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AggregateAccruals not implemented")
}
func (UnimplementedFinEventServer) BatchInsertAccruals(context.Context, *BatchInsertAccrualsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchInsertAccruals not implemented")
}
func (UnimplementedFinEventServer) GenerateAccrualPDF(context.Context, *GetRequest) (*FileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateAccrualPDF not implemented")
}
func (UnimplementedFinEventServer) ListProducts(context.Context, *ListRequest) (*ListProductsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProducts not implemented")
}
func (UnimplementedFinEventServer) ListPositions(context.Context, *ListRequest) (*ListPositionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPositions not implemented")
}
func (UnimplementedFinEventServer) UpdatePosition(context.Context, *Position) (*Position, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePosition not implemented")
}
func (UnimplementedFinEventServer) BatchInsertPositions(context.Context, *BatchInsertPositionsRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchInsertPositions not implemented")
}
func (UnimplementedFinEventServer) ListArticles(context.Context, *ListArticlesRequest) (*ListArticlesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListArticles not implemented")
}
func (UnimplementedFinEventServer) GetArticle(context.Context, *GetRequest) (*Article, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetArticle not implemented")
}
func (UnimplementedFinEventServer) CreateArticle(context.Context, *Article) (*Article, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateArticle not implemented")
}
func (UnimplementedFinEventServer) UpdateArticle(context.Context, *Article) (*Article, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateArticle not implemented")
}
func (UnimplementedFinEventServer) DeleteArticle(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteArticle not implemented")
}
func (UnimplementedFinEventServer) ListAllocations(context.Context, *ListRequest) (*ListAllocationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAllocations not implemented")
}
func (UnimplementedFinEventServer) CreateAllocation(context.Context, *Allocation) (*Allocation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAllocation not implemented")
}
func (UnimplementedFinEventServer) mustEmbedUnimplementedFinEventServer() {}

// UnsafeFinEventServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FinEventServer will
// result in compilation errors.
type UnsafeFinEventServer interface {
	mustEmbedUnimplementedFinEventServer()
}

func RegisterFinEventServer(s grpc.ServiceRegistrar, srv FinEventServer) {
	s.RegisterService(&FinEvent_ServiceDesc, srv)
}

func _FinEvent_ListSignatures_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).ListSignatures(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/ListSignatures",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).ListSignatures(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_ListComments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).ListComments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/ListComments",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).ListComments(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_CreateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Comment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).CreateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/CreateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).CreateComment(ctx, req.(*Comment))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_UpdateComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Comment)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).UpdateComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/UpdateComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).UpdateComment(ctx, req.(*Comment))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_DeleteComment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).DeleteComment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/DeleteComment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).DeleteComment(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_CreatePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Permission)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).CreatePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/CreatePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).CreatePermission(ctx, req.(*Permission))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_ListPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).ListPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/ListPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).ListPermissions(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_DeletePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).DeletePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/DeletePermission",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).DeletePermission(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_ListActions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).ListActions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/ListActions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).ListActions(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_ListTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).ListTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/ListTransfers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).ListTransfers(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_GetTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).GetTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/GetTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).GetTransfer(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_CreateTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transfer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).CreateTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/CreateTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).CreateTransfer(ctx, req.(*Transfer))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_AllocateTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AllocateTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).AllocateTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/AllocateTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).AllocateTransfer(ctx, req.(*AllocateTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_BatchInsertTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).BatchInsertTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/BatchInsertTransfers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).BatchInsertTransfers(ctx, req.(*BatchInsertTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_UpdateTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transfer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).UpdateTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/UpdateTransfer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).UpdateTransfer(ctx, req.(*Transfer))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_AggregateTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).AggregateTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/AggregateTransfers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).AggregateTransfers(ctx, req.(*AggregateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_ListAccruals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).ListAccruals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/ListAccruals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).ListAccruals(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_GetAccrual_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).GetAccrual(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/GetAccrual",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).GetAccrual(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_CreateAccrual_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Accrual)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).CreateAccrual(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/CreateAccrual",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).CreateAccrual(ctx, req.(*Accrual))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_UpdateAccrual_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Accrual)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).UpdateAccrual(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/UpdateAccrual",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).UpdateAccrual(ctx, req.(*Accrual))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_AggregateAccruals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AggregateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).AggregateAccruals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/AggregateAccruals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).AggregateAccruals(ctx, req.(*AggregateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_BatchInsertAccruals_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertAccrualsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).BatchInsertAccruals(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/BatchInsertAccruals",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).BatchInsertAccruals(ctx, req.(*BatchInsertAccrualsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_GenerateAccrualPDF_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).GenerateAccrualPDF(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/GenerateAccrualPDF",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).GenerateAccrualPDF(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_ListProducts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).ListProducts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/ListProducts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).ListProducts(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_ListPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).ListPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/ListPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).ListPositions(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_UpdatePosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Position)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).UpdatePosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/UpdatePosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).UpdatePosition(ctx, req.(*Position))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_BatchInsertPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertPositionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).BatchInsertPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/BatchInsertPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).BatchInsertPositions(ctx, req.(*BatchInsertPositionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_ListArticles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListArticlesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).ListArticles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/ListArticles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).ListArticles(ctx, req.(*ListArticlesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_GetArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).GetArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/GetArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).GetArticle(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_CreateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Article)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).CreateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/CreateArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).CreateArticle(ctx, req.(*Article))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_UpdateArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Article)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).UpdateArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/UpdateArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).UpdateArticle(ctx, req.(*Article))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_DeleteArticle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).DeleteArticle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/DeleteArticle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).DeleteArticle(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_ListAllocations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).ListAllocations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/ListAllocations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).ListAllocations(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FinEvent_CreateAllocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Allocation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FinEventServer).CreateAllocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/FinEvent/CreateAllocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FinEventServer).CreateAllocation(ctx, req.(*Allocation))
	}
	return interceptor(ctx, in, info, handler)
}

// FinEvent_ServiceDesc is the grpc.ServiceDesc for FinEvent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FinEvent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "FinEvent",
	HandlerType: (*FinEventServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSignatures",
			Handler:    _FinEvent_ListSignatures_Handler,
		},
		{
			MethodName: "ListComments",
			Handler:    _FinEvent_ListComments_Handler,
		},
		{
			MethodName: "CreateComment",
			Handler:    _FinEvent_CreateComment_Handler,
		},
		{
			MethodName: "UpdateComment",
			Handler:    _FinEvent_UpdateComment_Handler,
		},
		{
			MethodName: "DeleteComment",
			Handler:    _FinEvent_DeleteComment_Handler,
		},
		{
			MethodName: "CreatePermission",
			Handler:    _FinEvent_CreatePermission_Handler,
		},
		{
			MethodName: "ListPermissions",
			Handler:    _FinEvent_ListPermissions_Handler,
		},
		{
			MethodName: "DeletePermission",
			Handler:    _FinEvent_DeletePermission_Handler,
		},
		{
			MethodName: "ListActions",
			Handler:    _FinEvent_ListActions_Handler,
		},
		{
			MethodName: "ListTransfers",
			Handler:    _FinEvent_ListTransfers_Handler,
		},
		{
			MethodName: "GetTransfer",
			Handler:    _FinEvent_GetTransfer_Handler,
		},
		{
			MethodName: "CreateTransfer",
			Handler:    _FinEvent_CreateTransfer_Handler,
		},
		{
			MethodName: "AllocateTransfer",
			Handler:    _FinEvent_AllocateTransfer_Handler,
		},
		{
			MethodName: "BatchInsertTransfers",
			Handler:    _FinEvent_BatchInsertTransfers_Handler,
		},
		{
			MethodName: "UpdateTransfer",
			Handler:    _FinEvent_UpdateTransfer_Handler,
		},
		{
			MethodName: "AggregateTransfers",
			Handler:    _FinEvent_AggregateTransfers_Handler,
		},
		{
			MethodName: "ListAccruals",
			Handler:    _FinEvent_ListAccruals_Handler,
		},
		{
			MethodName: "GetAccrual",
			Handler:    _FinEvent_GetAccrual_Handler,
		},
		{
			MethodName: "CreateAccrual",
			Handler:    _FinEvent_CreateAccrual_Handler,
		},
		{
			MethodName: "UpdateAccrual",
			Handler:    _FinEvent_UpdateAccrual_Handler,
		},
		{
			MethodName: "AggregateAccruals",
			Handler:    _FinEvent_AggregateAccruals_Handler,
		},
		{
			MethodName: "BatchInsertAccruals",
			Handler:    _FinEvent_BatchInsertAccruals_Handler,
		},
		{
			MethodName: "GenerateAccrualPDF",
			Handler:    _FinEvent_GenerateAccrualPDF_Handler,
		},
		{
			MethodName: "ListProducts",
			Handler:    _FinEvent_ListProducts_Handler,
		},
		{
			MethodName: "ListPositions",
			Handler:    _FinEvent_ListPositions_Handler,
		},
		{
			MethodName: "UpdatePosition",
			Handler:    _FinEvent_UpdatePosition_Handler,
		},
		{
			MethodName: "BatchInsertPositions",
			Handler:    _FinEvent_BatchInsertPositions_Handler,
		},
		{
			MethodName: "ListArticles",
			Handler:    _FinEvent_ListArticles_Handler,
		},
		{
			MethodName: "GetArticle",
			Handler:    _FinEvent_GetArticle_Handler,
		},
		{
			MethodName: "CreateArticle",
			Handler:    _FinEvent_CreateArticle_Handler,
		},
		{
			MethodName: "UpdateArticle",
			Handler:    _FinEvent_UpdateArticle_Handler,
		},
		{
			MethodName: "DeleteArticle",
			Handler:    _FinEvent_DeleteArticle_Handler,
		},
		{
			MethodName: "ListAllocations",
			Handler:    _FinEvent_ListAllocations_Handler,
		},
		{
			MethodName: "CreateAllocation",
			Handler:    _FinEvent_CreateAllocation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/fin_event.proto",
}
