// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v4.24.3
// source: proto/operation_accruals.proto

package _go

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationAccruals struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Operation *Operation            `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	Accruals  []*AccrualAllocations `protobuf:"bytes,2,rep,name=accruals,proto3" json:"accruals,omitempty"`
}

func (x *OperationAccruals) Reset() {
	*x = OperationAccruals{}
	mi := &file_proto_operation_accruals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationAccruals) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationAccruals) ProtoMessage() {}

func (x *OperationAccruals) ProtoReflect() protoreflect.Message {
	mi := &file_proto_operation_accruals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationAccruals.ProtoReflect.Descriptor instead.
func (*OperationAccruals) Descriptor() ([]byte, []int) {
	return file_proto_operation_accruals_proto_rawDescGZIP(), []int{0}
}

func (x *OperationAccruals) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

func (x *OperationAccruals) GetAccruals() []*AccrualAllocations {
	if x != nil {
		return x.Accruals
	}
	return nil
}

var File_proto_operation_accruals_proto protoreflect.FileDescriptor

var file_proto_operation_accruals_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x61, 0x63, 0x63, 0x72, 0x75, 0x61, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x61,
	0x63, 0x63, 0x72, 0x75, 0x61, 0x6c, 0x5f, 0x61, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6e, 0x0a, 0x11, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x63, 0x63, 0x72, 0x75, 0x61, 0x6c, 0x73, 0x12, 0x28, 0x0a,
	0x09, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x09, 0x6f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2f, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x72, 0x75,
	0x61, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x41, 0x63, 0x63, 0x72,
	0x75, 0x61, 0x6c, 0x41, 0x6c, 0x6c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x08,
	0x61, 0x63, 0x63, 0x72, 0x75, 0x61, 0x6c, 0x73, 0x42, 0x26, 0x5a, 0x24, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x6c, 0x65, 0x78, 0x4b, 0x65, 0x6e, 0x62, 0x6f,
	0x2f, 0x64, 0x69, 0x63, 0x74, 0x75, 0x6d, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_operation_accruals_proto_rawDescOnce sync.Once
	file_proto_operation_accruals_proto_rawDescData = file_proto_operation_accruals_proto_rawDesc
)

func file_proto_operation_accruals_proto_rawDescGZIP() []byte {
	file_proto_operation_accruals_proto_rawDescOnce.Do(func() {
		file_proto_operation_accruals_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_operation_accruals_proto_rawDescData)
	})
	return file_proto_operation_accruals_proto_rawDescData
}

var file_proto_operation_accruals_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_operation_accruals_proto_goTypes = []any{
	(*OperationAccruals)(nil),  // 0: OperationAccruals
	(*Operation)(nil),          // 1: Operation
	(*AccrualAllocations)(nil), // 2: AccrualAllocations
}
var file_proto_operation_accruals_proto_depIdxs = []int32{
	1, // 0: OperationAccruals.operation:type_name -> Operation
	2, // 1: OperationAccruals.accruals:type_name -> AccrualAllocations
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_operation_accruals_proto_init() }
func file_proto_operation_accruals_proto_init() {
	if File_proto_operation_accruals_proto != nil {
		return
	}
	file_proto_operation_proto_init()
	file_proto_accrual_allocations_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_operation_accruals_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_operation_accruals_proto_goTypes,
		DependencyIndexes: file_proto_operation_accruals_proto_depIdxs,
		MessageInfos:      file_proto_operation_accruals_proto_msgTypes,
	}.Build()
	File_proto_operation_accruals_proto = out.File
	file_proto_operation_accruals_proto_rawDesc = nil
	file_proto_operation_accruals_proto_goTypes = nil
	file_proto_operation_accruals_proto_depIdxs = nil
}
