// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.24.3
// source: proto/plugin_service.proto

package _go

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	PluginService_ListObjectSources_FullMethodName  = "/PluginService/ListObjectSources"
	PluginService_GetLatestSource_FullMethodName    = "/PluginService/GetLatestSource"
	PluginService_CreateObjectSource_FullMethodName = "/PluginService/CreateObjectSource"
	PluginService_DeleteObjectSource_FullMethodName = "/PluginService/DeleteObjectSource"
	PluginService_CreateService_FullMethodName      = "/PluginService/CreateService"
	PluginService_ListServices_FullMethodName       = "/PluginService/ListServices"
	PluginService_GetService_FullMethodName         = "/PluginService/GetService"
	PluginService_UpdateService_FullMethodName      = "/PluginService/UpdateService"
	PluginService_CreateServiceRun_FullMethodName   = "/PluginService/CreateServiceRun"
	PluginService_UpdateServiceRun_FullMethodName   = "/PluginService/UpdateServiceRun"
	PluginService_GetServiceRun_FullMethodName      = "/PluginService/GetServiceRun"
	PluginService_ListServiceRuns_FullMethodName    = "/PluginService/ListServiceRuns"
	PluginService_RunService_FullMethodName         = "/PluginService/RunService"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PluginServiceClient interface {
	// * Sources
	ListObjectSources(ctx context.Context, in *ListObjectSourcesRequest, opts ...grpc.CallOption) (*ListObjectSourcesResponse, error)
	GetLatestSource(ctx context.Context, in *GetLatestSourceRequest, opts ...grpc.CallOption) (*ObjectSource, error)
	CreateObjectSource(ctx context.Context, in *ObjectSource, opts ...grpc.CallOption) (*ObjectSource, error)
	DeleteObjectSource(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	// * Service
	CreateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Service, error)
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*Service, error)
	UpdateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Service, error)
	// * Service Runs
	CreateServiceRun(ctx context.Context, in *ServiceRun, opts ...grpc.CallOption) (*ServiceRun, error)
	UpdateServiceRun(ctx context.Context, in *ServiceRun, opts ...grpc.CallOption) (*ServiceRun, error)
	GetServiceRun(ctx context.Context, in *GetServiceRunRequest, opts ...grpc.CallOption) (*ServiceRun, error)
	ListServiceRuns(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListServiceRunsResponse, error)
	RunService(ctx context.Context, in *RunServiceRequest, opts ...grpc.CallOption) (*ServiceRun, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) ListObjectSources(ctx context.Context, in *ListObjectSourcesRequest, opts ...grpc.CallOption) (*ListObjectSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObjectSourcesResponse)
	err := c.cc.Invoke(ctx, PluginService_ListObjectSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetLatestSource(ctx context.Context, in *GetLatestSourceRequest, opts ...grpc.CallOption) (*ObjectSource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectSource)
	err := c.cc.Invoke(ctx, PluginService_GetLatestSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) CreateObjectSource(ctx context.Context, in *ObjectSource, opts ...grpc.CallOption) (*ObjectSource, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ObjectSource)
	err := c.cc.Invoke(ctx, PluginService_CreateObjectSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) DeleteObjectSource(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, PluginService_DeleteObjectSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) CreateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, PluginService_CreateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, PluginService_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetService(ctx context.Context, in *GetServiceRequest, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, PluginService_GetService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) UpdateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*Service, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Service)
	err := c.cc.Invoke(ctx, PluginService_UpdateService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) CreateServiceRun(ctx context.Context, in *ServiceRun, opts ...grpc.CallOption) (*ServiceRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceRun)
	err := c.cc.Invoke(ctx, PluginService_CreateServiceRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) UpdateServiceRun(ctx context.Context, in *ServiceRun, opts ...grpc.CallOption) (*ServiceRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceRun)
	err := c.cc.Invoke(ctx, PluginService_UpdateServiceRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) GetServiceRun(ctx context.Context, in *GetServiceRunRequest, opts ...grpc.CallOption) (*ServiceRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceRun)
	err := c.cc.Invoke(ctx, PluginService_GetServiceRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) ListServiceRuns(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListServiceRunsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServiceRunsResponse)
	err := c.cc.Invoke(ctx, PluginService_ListServiceRuns_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) RunService(ctx context.Context, in *RunServiceRequest, opts ...grpc.CallOption) (*ServiceRun, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServiceRun)
	err := c.cc.Invoke(ctx, PluginService_RunService_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility
type PluginServiceServer interface {
	// * Sources
	ListObjectSources(context.Context, *ListObjectSourcesRequest) (*ListObjectSourcesResponse, error)
	GetLatestSource(context.Context, *GetLatestSourceRequest) (*ObjectSource, error)
	CreateObjectSource(context.Context, *ObjectSource) (*ObjectSource, error)
	DeleteObjectSource(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	// * Service
	CreateService(context.Context, *Service) (*Service, error)
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	GetService(context.Context, *GetServiceRequest) (*Service, error)
	UpdateService(context.Context, *Service) (*Service, error)
	// * Service Runs
	CreateServiceRun(context.Context, *ServiceRun) (*ServiceRun, error)
	UpdateServiceRun(context.Context, *ServiceRun) (*ServiceRun, error)
	GetServiceRun(context.Context, *GetServiceRunRequest) (*ServiceRun, error)
	ListServiceRuns(context.Context, *ListRequest) (*ListServiceRunsResponse, error)
	RunService(context.Context, *RunServiceRequest) (*ServiceRun, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have forward compatible implementations.
type UnimplementedPluginServiceServer struct {
}

func (UnimplementedPluginServiceServer) ListObjectSources(context.Context, *ListObjectSourcesRequest) (*ListObjectSourcesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListObjectSources not implemented")
}
func (UnimplementedPluginServiceServer) GetLatestSource(context.Context, *GetLatestSourceRequest) (*ObjectSource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestSource not implemented")
}
func (UnimplementedPluginServiceServer) CreateObjectSource(context.Context, *ObjectSource) (*ObjectSource, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateObjectSource not implemented")
}
func (UnimplementedPluginServiceServer) DeleteObjectSource(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteObjectSource not implemented")
}
func (UnimplementedPluginServiceServer) CreateService(context.Context, *Service) (*Service, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateService not implemented")
}
func (UnimplementedPluginServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedPluginServiceServer) GetService(context.Context, *GetServiceRequest) (*Service, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetService not implemented")
}
func (UnimplementedPluginServiceServer) UpdateService(context.Context, *Service) (*Service, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateService not implemented")
}
func (UnimplementedPluginServiceServer) CreateServiceRun(context.Context, *ServiceRun) (*ServiceRun, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateServiceRun not implemented")
}
func (UnimplementedPluginServiceServer) UpdateServiceRun(context.Context, *ServiceRun) (*ServiceRun, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateServiceRun not implemented")
}
func (UnimplementedPluginServiceServer) GetServiceRun(context.Context, *GetServiceRunRequest) (*ServiceRun, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetServiceRun not implemented")
}
func (UnimplementedPluginServiceServer) ListServiceRuns(context.Context, *ListRequest) (*ListServiceRunsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServiceRuns not implemented")
}
func (UnimplementedPluginServiceServer) RunService(context.Context, *RunServiceRequest) (*ServiceRun, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunService not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_ListObjectSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).ListObjectSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_ListObjectSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).ListObjectSources(ctx, req.(*ListObjectSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetLatestSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetLatestSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetLatestSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetLatestSource(ctx, req.(*GetLatestSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_CreateObjectSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ObjectSource)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).CreateObjectSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_CreateObjectSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).CreateObjectSource(ctx, req.(*ObjectSource))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_DeleteObjectSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).DeleteObjectSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_DeleteObjectSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).DeleteObjectSource(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_CreateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).CreateService(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetService(ctx, req.(*GetServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_UpdateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).UpdateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_UpdateService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).UpdateService(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_CreateServiceRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRun)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).CreateServiceRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_CreateServiceRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).CreateServiceRun(ctx, req.(*ServiceRun))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_UpdateServiceRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceRun)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).UpdateServiceRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_UpdateServiceRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).UpdateServiceRun(ctx, req.(*ServiceRun))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_GetServiceRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).GetServiceRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_GetServiceRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).GetServiceRun(ctx, req.(*GetServiceRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_ListServiceRuns_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).ListServiceRuns(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_ListServiceRuns_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).ListServiceRuns(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_RunService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).RunService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_RunService_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).RunService(ctx, req.(*RunServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListObjectSources",
			Handler:    _PluginService_ListObjectSources_Handler,
		},
		{
			MethodName: "GetLatestSource",
			Handler:    _PluginService_GetLatestSource_Handler,
		},
		{
			MethodName: "CreateObjectSource",
			Handler:    _PluginService_CreateObjectSource_Handler,
		},
		{
			MethodName: "DeleteObjectSource",
			Handler:    _PluginService_DeleteObjectSource_Handler,
		},
		{
			MethodName: "CreateService",
			Handler:    _PluginService_CreateService_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _PluginService_ListServices_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _PluginService_GetService_Handler,
		},
		{
			MethodName: "UpdateService",
			Handler:    _PluginService_UpdateService_Handler,
		},
		{
			MethodName: "CreateServiceRun",
			Handler:    _PluginService_CreateServiceRun_Handler,
		},
		{
			MethodName: "UpdateServiceRun",
			Handler:    _PluginService_UpdateServiceRun_Handler,
		},
		{
			MethodName: "GetServiceRun",
			Handler:    _PluginService_GetServiceRun_Handler,
		},
		{
			MethodName: "ListServiceRuns",
			Handler:    _PluginService_ListServiceRuns_Handler,
		},
		{
			MethodName: "RunService",
			Handler:    _PluginService_RunService_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugin_service.proto",
}
