name: dictum_proto
version: 1.0.0
description: Буффер между протоколами бекенда и фронтенда Dictum.

environment:
  sdk: '>=2.12.0 <3.10.0' 

dependencies:
  protobuf:
  grpc:
  protoc_plugin: ^21.1.1
